import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { signIn, useSession } from "next-auth/react";
import Axios from "axios";
import { FaGithub } from "react-icons/fa";
import { useEffect, useState } from "react";

export default function Home() {
  const { data: session } = useSession();
  const [mob, setMob] = useState<string>("");
  const [emails, setEmails] = useState<string>("");
  const [cc, setCC] = useState<string>("");
  const [writeup, setWriteup] = useState<string>("general");
  useEffect(() => {}, [session]);

  console.log("data: ", session);
  return (
    <div className={styles.container}>
      <Head>
        <title>We Get Sponsi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={styles.title}>
          Welcome to <a href=""> TS-Mailer! </a>
        </h1>
        {!session ? (
          <button onClick={() => signIn("google")}>Sign In With Google</button>
        ) : (
          <>
            <div>
              <div className={styles.card}>
                <label htmlFor="phone">Mobile: </label>
                <input
                  className={styles.inpBox}
                  id="phone"
                  onChange={(e) => {
                    setMob(e.target.value);
                  }}
                />
              </div>
              <br />
              <div className={styles.card}>
                <label htmlFor="writeup">Writeup: </label>
                <select
                  className={styles.inpBox}
                  id="writeup"
                  onChange={(e) => setWriteup(e.target.value)}
                >
                  <option className={styles.inpBox} value="general">
                    General
                  </option>
                  <option className={styles.inpBox} value="hackathon">
                    {" "}
                    Hackathon{" "}
                  </option>
                  <option className={styles.inpBox} value="coding-platform">
                    {" "}
                    Coding Platform{" "}
                  </option>
                </select>
              </div>
              <br />
              <div className={styles.card}>
                <label htmlFor="emails">Emails: </label>
                <input
                  className={styles.inpBox}
                  type="text"
                  id="emails"
                  onChange={(e) => setEmails(e.target.value)}
                />
              </div>
              <br />
              <div className={styles.card}>
                <label htmlFor="cc">CC: </label>
                <input
                  className={styles.inpBox}
                  type="text"
                  id="cc"
                  onChange={(e) => setCC(e.target.value)}
                />
              </div>
              <br />
              <button
                className={styles.card}
                onClick={() => {
                  Axios({
                    method: "post",
                    url: "/api/sendmail",
                    withCredentials: true,
                    data: {
                      phone: mob,
                      writeup: writeup,
                      emails: emails.split(","),
                      cc: cc.split(","),
                    },
                  }).then((res) => {
                    if (res.data.error) {
                      alert(res.data.error);
                    } else {
                      alert(res.data);
                    }
                  });
                }}
              >
                Send Request
              </button>
              <br />
            </div>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <p>
          <span className={styles.logo}>
            <a
              href="https://github.com/techsavvyash"
              target="_blank"
              rel="noreferrer"
            >
              Made by /techsavvyash
            </a>
          </span>
        </p>
      </footer>
    </div>
  );
}
