import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSession } from "next-auth/react";
import Axios from "axios";

export default function Home() {
  const { data: session } = useSession();
  console.log("data: ", session);
  return (
    <div className={styles.container}>
      <Head>
        <title>We Get Sponsi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={styles.title}>
          Welcome to <a href=""> TS-Mailer! </a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <div className={styles.grid}>
          <button
            onClick={() => {
              Axios({
                method: "post",
                url: "/api/sendmail",
                withCredentials: true,
                data: {
                  name: "Yash Mittal",
                  phone: "1234567890",
                  writeup: "general",
                },
              }).then((res) => res.data);
            }}
          >
            {" "}
            Send Request{" "}
          </button>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
