import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { signIn, useSession } from "next-auth/react";
import Axios from "axios";
import { FaGithub } from "react-icons/fa";
import { useEffect, useState } from "react";

export default function Home() {
  const { data: session } = useSession();
  const [mob, setMob] = useState<number>(0);
  const [writeup, setWriteup] = useState<string>("general");
  useEffect(() => {}, [session]);

  console.log("data: ", session);
  return (
    <div className={styles.container}>
      <Head>
        <title>We Get Sponsi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={styles.title}>
          Welcome to <a href=""> TS-Mailer! </a>
        </h1>
        {!session ? (
          <button onClick={() => signIn("google")}>Sign In With Google</button>
        ) : (
          <>
            <div className={styles.grid}>
              <div>
                <label htmlFor="phone">Mobile: </label>
                <input id="phone" />
              </div>
              <div>
                <label htmlFor="writeup">Writeup: </label>
                <select id="writeup">
                  <option value="general">General</option>
                  <option value="hackathon"> Hackathon </option>
                  <option value="coding-platform"> Coding Platform </option>
                </select>
              </div>
              <div>
                <label htmlFor="emails">Emails: </label>
                <input type="text" id="emails" />
              </div>
              <div>
                <label htmlFor="cc">CC: </label>
                <input type="text" id="cc" />
              </div>
              <button
                onClick={() => {
                  Axios({
                    method: "post",
                    url: "/api/sendmail",
                    withCredentials: true,
                    data: {
                      name: "Yash Mittal",
                      phone: "1234567890",
                      writeup: "hackathon",
                      emails: ["techsavvyash@gmail.com", "yami8b@gmail.com"],
                      cc: [
                        "yaadonkabackup@gmail.com",
                        "yash_12012002@nitkkr.ac.in",
                      ],
                    },
                  }).then((res) => res.data);
                }}
              >
                Send Request
              </button>
            </div>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <p>
          <span className={styles.logo}>
            <a
              href="https://github.com/techsavvyash"
              target="_blank"
              rel="noreferrer"
            >
              Made by /techsavvyash
            </a>
          </span>
        </p>
      </footer>
    </div>
  );
}
